export type Locale = "cs" | "en" | "ja";

export const COPY = {
  cs: {
    nav: {
      tea: "Nápoje",
      pipes: "Dýmky",
      games: "Hry",
      fare: "Nabídník",
      board: "Nástěnka",
      contact: "Kontakt",
      shop: "Nakupovat",
      shopSoon: "Připravujeme",
      book: "Rezervace",
      menu: "Menu",
    },
    dock: {
      where: "Kde nás najdete",
      hours: "Otevírací doba",
      call: "Zavolat",
      nav: "Navigace",
    },
    hero: {
      kicker: "Pár kroků od Karlova náměstí",
      title: "Čaj.\nDýmka.\nHry.\nGatcha.",
      italic: "Ulice nic neřekne. Pak pasáž. Pak jiný čas.",
      lead: "Suterén v Myslíkově ul. Čaj, dýmka, žádný spěch.",
      cta: "Rezervovat stůl",
      maps: "Jak se k nám dostanete",
    },
    mosaic: {
      offer: "Čaje a drinky",
      offerSub: "Čaje, alkohol i nealko, jídlo a speciality.",
      pipes: "Dýmky",
      pipesSub: "Vyzkoušet, koupit, nebo si půjčit dýmku s sebou.",
      gatcha: "Gatcha",
      gatchaSub: "Zatočení po účtence.",
      games: "Deskové hry",
      gamesSub: "Knihovna her k zapůjčení.",
    },
    taste: {
      kicker: "Naše oblíbené speciality",
      title: "V Buddhovi ochutnej.",
      more: "Zjistit více",
      sakurac: "Sakurač",
      sakuracT: "Jemná japonská klasika.",
      waysa: "Waysa",
      waysaT: "Přírodní energie z Amazonie.",
      mead: "Norské medoviny",
      meadT: "Severské medoviny pro výjimečné večery.",
    },
    bookBand: {
      kicker: "Rezervace",
      title: "Rychle a jednoduše.",
      lead: "Den, vlna, stůl. 1–4 hosté ihned, 5–8 potvrdí obsluha.",
      cta: "Rezervovat stůl",
    },
    promo: {
      kicker: "Promo série",
      title: "Sál, který dýchá.",
      all: "Celá série →",
    },
    reasons: {
      kicker: "Proč přijít právě dnes",
      title: "Ve dvou. S přáteli. Ve větší skupině.",
      duo: "Ve dvou",
      duoT: "Jedna konvice, dva šálky. Klidný večer bez spěchu.",
      friends: "S přáteli",
      friendsT: "Hry, čaj a dýmka. Posezení, které má čas.",
      party: "Větší skupina",
      partyT: "5–8 hostů rezervujte online. 9 a více telefonicky.",
    },
    pipeSec: {
      kicker: "Dýmka",
      title: "Večer, který se nepočítá na minuty.",
      body: "Adalya 229 Kč, Cult a Serbetli 289 Kč. Pouze k nápoji, od 18 let. Výhodněji než shisha bar o ulici dál. Dýmku si můžete také půjčit s sebou.",
    },
    gamesSec: {
      kicker: "Deskové hry",
      title: "Půjčte si a hrajte.",
      body: "Knihovna her na místě. Osadníci, Carcassonne a další desítky titulů ve vitríně — vratná záloha 200 Kč.",
      cta: "Kompletní seznam her →",
    },
    gatchaSec: {
      kicker: "Gatcha",
      title: "Zatočení po účtence.",
      from: "Účtenka od",
      small: "1 500 Kč",
      eqS: "= menší zatočení.",
      from2: "Od",
      big: "2 000 Kč",
      eqL: "= velké.",
      note: "Odměna za návštěvu, ne automat.",
      cta: "Jak Gatcha funguje →",
    },
    hh: {
      badge: "Po–Čt · 13:00–15:00",
      kicker: "Happy hours",
      title: "Akce na dýmky.",
      deal: "1+1 za cenu jedné.",
      lead: "Přijďte s přáteli. Dvě dýmky za cenu jedné — platí se ta dražší, pokud nejsou stejné.",
      r1: "Objednávka najednou, do 15:00. Minimálně dva hosté.",
      r2: "Stejná kategorie, jinak se platí dražší dýmka.",
      r3: "Nekombinuje se s kartou „10. dýmka zdarma“.",
      cta: "Rezervovat odpoledne",
    },
    reviews: {
      kicker: "Hlasy ze sálu · 4,4 / 5",
      title: "Co o nás píší hosté.",
      prev: "Předchozí recenze",
      next: "Další recenze",
    },
    about: {
      kicker: "O nás",
      title: "Z lásky k čaji, cestám a lidem.",
      body: "Myslíkova vede od Vltavy k náměstí od dob Karla IV. Čajovna je pod ní — suterén, kam se chodí zpomalit. Čaj, dýmka, hry. Vchod z ulice přes pasáž Exafin.",
    },
    didge: {
      kicker: "Didgeridoo",
      title: "Nástroje, které mají duši.",
      body: "Autentické nástroje od Tomáše Dufka. K vyzkoušení v sále i k zakoupení.",
      cta: "Didgeridoo v obchodě →",
    },
    matcha: {
      badge: "Brzy končí",
      kicker: "Sezónní nabídka",
      title: "Matcha menu.",
      note: "Točená zmrzlina 120 g, nebo 3 kopečky 180 g. Až dojde točená, dáme kopeček 120 g.",
      book: "Rezervovat",
      ig: "Instagram",
      n1: "Matcha float",
      t1: "Našlehaná matcha se sodou, jahodovým sirupem a kopečkem matcha zmrzliny.",
      n2: "Opilá jahoda",
      t2: "Vodka a ořechový likér, drcené jahody, třtinový cukr, kopeček matcha zmrzliny.",
      n3: "Pivo s matchou",
      t3: "Pololežák Oxymoron 13° s našlehanou matchou.",
      n4: "Matcha gin soda",
      t4: "Našlehaná matcha se sodou, jahodovým sirupem a panákem Roku ginu.",
      n5: "Matcha latté float",
      t5: "Studené matcha latté s kopečkem matcha zmrzliny.",
      n6: "Zmrzlinový pohár",
      t6: "Pohár matcha zmrzliny se šlehačkou a čerstvými jahodami.",
    },
    board: {
      kicker: "Nástěnka čajovny",
      rss: "RSS kanál →",
      tabs: "Desky nástěnky",
      news: "Čaj & akce",
      newsK: "Novinky z konvice",
      ads: "Inzerce",
      adsK: "Veřejná nástěnka",
      forum: "Fórum hráčů",
      forumK: "Členské · deskovky",
      close: "Zavřít",
      postGame: "Vyvěsit hru",
      postNote: "Vyvěsit lístek",
      phTitleGame: "Jaká hra, kdy",
      phTitle: "Nadpis inzerátu",
      phBody: "Krátký lístek, max 280.",
      phNick: "Přezdívka hráče",
      phName: "Jméno",
      pin: "Připíchnout",
      empty: "Zatím prázdné. Vyvěste první lístek.",
    },
    contact: {
      kicker: "Kdy a kde",
      how: "Jak se k nám dostanete",
      s1: "1. Od Karlova mostu podél Vltavy. U Tančícího domu zabočte na Myslíkovu — pár minut od řeky.",
      s2: "2. Z ulice to není vidět. Myslíkova 174/23 — hledejte pasáž Exafin, jako byste věděli.",
      s3: "3. Schody dolů. Čajovna je pod městem.",
      pass: "Praha 1 – Nové Město · vchod znají ti, kdo vědí · pasáž Exafin, suterén",
      exafin: "Budova Exafin — velký nápis ve štítu. Mezi Karlovým náměstím a nábřežím.",
    },
    footer: {
      motto: "Čaj spojuje lidi.",
      contact: "Kontakt",
      hours: "Otevírací doba",
      hoursShort: "Po–Čt 13–22 · Pá 13–23\nSo 14–23 · Ne 14–22",
      how: "Jak k nám",
      metro: "Po Karlově mostě podél Vltavy · Tančící dům, Myslíkova",
      tram: "Metro B / tram: Karlovo náměstí · Myslíkova",
      door: "Z ulice nic. Pasáž Exafin. Schody dolů.",
      map: "Zobrazit mapu →",
      promo: "Promo série",
      share: "Náhledy sítí",
      partners: "Spolupracujeme",
      staff: "Pro obsluhu",
      icons: {
        tea: "Čaje a drinky",
        teaD: "Čaje z celého světa, míchané drinky, medoviny.",
        pipes: "Vodní dýmky",
        pipesD: "Špičkové dýmky, prémiové tabáky.",
        games: "Deskové hry",
        gamesD: "Desítky her k zapůjčení na místě.",
        gatcha: "Gatcha",
        gatchaD: "Zatočení zdarma při splnění výše účtenky.",
        didge: "Didgeridoo",
        didgeD: "K vyzkoušení i na prodej.",
      },
      stories: {
        about: "O nás",
        aboutD: "Příběh Buddha čajovny. Místo vzniklé z lásky k čaji, cestám a lidem.",
        aboutC: "Přečíst příběh",
        didge: "Didgeridoo",
        didgeD: "Autentické nástroje od Tomáše Dufka. K vyzkoušení i k zakoupení.",
        didgeC: "Více informací",
        pipes: "Dýmky k prodeji i k zapůjčení",
        pipesD: "Nové i bazarové. Vyzkoušejte je u nás, odneste si je domů, nebo si je půjčte.",
        pipesC: "Prohlédnout",
      },
    },
    days: {
      Pondělí: "Pondělí",
      Úterý: "Úterý",
      Středa: "Středa",
      Čtvrtek: "Čtvrtek",
      Pátek: "Pátek",
      Sobota: "Sobota",
      Neděle: "Neděle",
    },
    book: {
      kicker: "Napište nám, kdy přijdete",
      title: "Rezervujte si stůl.",
      lead: "Den, vlna a stůl z plánku. 1–4 hosté potvrdíme ihned, 5–8 obsluha, 9 a více telefonicky. Vchod z ulice přes pasáž, budova Exafin.",
      day: "Den návštěvy",
      when: "Čas příchodu",
      party: "Počet osob",
      p78: "7–8: stůl M1 v Malé místnosti. Jinak dva stoly, nebo volejte.",
      p56: "5–6 potvrdí obsluha. Stoly V6, V3, V7 v Přední.",
      name: "Jméno rezervace",
      phone: "Telefon pro případ změny",
      phoneHint: "České číslo bez předvolby. Slovenské s +421.",
      email: "E-mail pro potvrzení",
      note: "Přání k rezervaci (dýmka, hra, koutek)",
      pick: "Vyberte stůl na plánku",
      reserve: "Rezervovat",
      free: "V této vlně je volných {n} stolů pro {p} {people}.",
      person: "osobu",
      people: "osob",
      hold: "držíte",
      ok: "Rezervace je potvrzena",
      wait: "Čeká na potvrzení obsluhy",
      dup: "Tuto rezervaci už evidujeme",
      waitBody: "Ozveme se. Skupina čeká na potvrzení stolu.",
      okBody: "Vchod z ulice přes pasáž, budova Exafin, do suterénu. Budeme vás čekat.",
      back: "Zpět na Buddha",
      all: "Celá čajovna",
      first: "Nejprve místnost, poté stůl.",
      sit: "Vybrané místo",
      backMap: "← celá čajovna",
      taken: "obsazeno",
      max: "max",
      upTo: "až {n} lidí",
      PHONE_INVALID: "České číslo stačí bez předvolby. Slovenské a zahraniční s +.",
      NAME_INVALID: "Název rezervace — pro koho je stůl.",
      EMAIL_INVALID: "E-mail pro potvrzení.",
      PARTY_SIZE: "Online bereme 1–8 lidí. Víc? Zavolejte.",
      CALL: "Na 9 a více zavolejte +420 222 515 616.",
      TABLE: "Vyberte stůl na plánku.",
      TABLE_SMALL: "Tento stůl je pro vaši skupinu malý. Zvolte větší, nebo snižte počet osob.",
      TABLE_TAKEN: "Tento stůl je v dané vlně obsazený.",
    },
    waves: {
      "15:00": "Odpolední čaj",
      "17:30": "Pomalu se stmívá",
      "19:30": "Večer u konvice",
      "21:30": "Tichá poslední",
    },
    shop: {
      kicker: "Obchod čajovny",
      title: "Nákup k vyzvednutí.",
      lead: "Sakurač 0,3 l, Waysa 0,33 l, čaj a Wookah. Ceny jako v čajovně. Platba na místě, vyzvednutí na Myslíkově.",
      soonKicker: "Obchod čajovny",
      soonTitle: "Připravujeme e-shop.",
      soonLead: "Čaje, Waysa, náustky, Wookah a didgeridoo. Zatím nakoupíte u nás v čajovně. Online nabídku spustíme, až bude připravená k vyzvednutí.",
      soonCta: "Rezervovat stůl",
    },
  },
  en: {
    nav: {
      tea: "Drinks",
      pipes: "Hookah",
      games: "Games",
      fare: "Menu",
      board: "Board",
      contact: "Visit",
      shop: "Shop",
      shopSoon: "Coming soon",
      book: "Reserve",
      menu: "Menu",
    },
    dock: {
      where: "Find us",
      hours: "Hours",
      call: "Call",
      nav: "Directions",
    },
    hero: {
      kicker: "A few steps from Charles Square",
      title: "Tea.\nHookah.\nGames.\nGatcha.",
      italic: "The street gives nothing away. Then the passage. Then another time.",
      lead: "A cellar on Myslíkova street. Tea, hookah, no hurry.",
      cta: "Reserve a table",
      maps: "Get directions",
    },
    mosaic: {
      offer: "Tea & drinks",
      offerSub: "Tea, drinks, food and house specials.",
      pipes: "Hookah",
      pipesSub: "Try, buy, or take a hookah home.",
      gatcha: "Gatcha",
      gatchaSub: "Spin and win.",
      games: "Board games",
      gamesSub: "A large library. Borrow and play.",
    },
    taste: {
      kicker: "House favourites",
      title: "Taste it at Buddha.",
      more: "Find out more",
      sakurac: "Sakurač",
      sakuracT: "A soft Japanese classic.",
      waysa: "Waysa",
      waysaT: "Natural energy from the Amazon.",
      mead: "Norwegian mead",
      meadT: "Nordic mead for a slower evening.",
    },
    bookBand: {
      kicker: "Reservations",
      title: "Quick and simple.",
      lead: "Day, evening wave, table. 1–4 confirmed now, 5–8 by staff.",
      cta: "Reserve now",
    },
    promo: {
      kicker: "Promo series",
      title: "A hall that breathes.",
      all: "Full series →",
    },
    reasons: {
      kicker: "Why come today",
      title: "As two. With friends. A larger group.",
      duo: "As two",
      duoT: "One pot. Two cups. Whoever stole the third stays quiet.",
      friends: "With friends",
      friendsT: "Games, tea, hookah. The dice sit as a fourth player.",
      party: "Larger group",
      partyT: "5–8 reserve online. 9+ call — one of you already has the phone.",
    },
    pipeSec: {
      kicker: "Hookah",
      title: "An evening not counted in minutes.",
      body: "Adalya 229 Kč, Cult and Serbetli 289 Kč. Only with a drink, 18+. Cheaper than the shisha bar a street away. You can also take a hookah home — we've done it for years.",
    },
    gamesSec: {
      kicker: "Board games",
      title: "Borrow and play.",
      body: "A large library on site. Catan, Dixit, Carcassonne, Party Alias and twenty more in the cabinet — 200 Kč deposit.",
      cta: "Full games list →",
    },
    gatchaSec: {
      kicker: "Gatcha",
      title: "Spin after the bill.",
      from: "From",
      small: "1,500 Kč",
      eqS: "= a small spin.",
      from2: "From",
      big: "2,000 Kč",
      eqL: "= a big one.",
      note: "A reward for coming, not a machine.",
      cta: "How Gatcha works →",
    },
    hh: {
      badge: "Mon–Thu · 13:00–15:00",
      kicker: "Happy hours",
      title: "Hookah deal.",
      deal: "1+1 for the price of one.",
      lead: "Come with friends. Two pipes, you pay for one — the pricier one if they differ.",
      r1: "Order together, before 15:00. At least two people.",
      r2: "Same price tier, or you pay the more expensive one.",
      r3: "Doesn’t stack with the “10th pipe free” card.",
      cta: "Reserve the afternoon",
    },
    reviews: {
      kicker: "Voices from the hall · 4.4 / 5",
      title: "Not us saying it.",
      prev: "Previous review",
      next: "Next review",
    },
    about: {
      kicker: "About",
      title: "From a love of tea, travel and people.",
      body: "Myslíkova has run from the river to the square since Charles IV. The tea house is underneath — a cellar to slow down. Tea, hookah, games. Street entrance through the Exafin passage.",
    },
    didge: {
      kicker: "Didgeridoo",
      title: "Instruments with a soul.",
      body: "Authentic instruments by Tomáš Dufek. To try in the hall and to buy.",
      cta: "Didgeridoo in the shop →",
    },
    matcha: {
      badge: "Ending soon",
      kicker: "Seasonal",
      title: "Matcha menu.",
      note: "Soft-serve 120 g, or 3 scoops 180 g. When the machine runs out, we serve a 120 g scoop.",
      book: "Reserve",
      ig: "Instagram",
      n1: "Matcha float",
      t1: "Whipped matcha with soda, strawberry syrup and a scoop of matcha ice cream.",
      n2: "Drunk strawberry",
      t2: "Vodka and nut liqueur, crushed strawberries, cane sugar, a scoop of matcha ice cream.",
      n3: "Beer with matcha",
      t3: "Oxymoron 13° pale lager with whipped matcha.",
      n4: "Matcha gin soda",
      t4: "Whipped matcha with soda, strawberry syrup and a shot of Roku gin.",
      n5: "Matcha latte float",
      t5: "Iced matcha latte with a scoop of matcha ice cream.",
      n6: "Ice-cream cup",
      t6: "Matcha ice cream with whipped cream and fresh strawberries.",
    },
    board: {
      kicker: "Tea-house board",
      rss: "RSS feed →",
      tabs: "Board lanes",
      news: "Tea & deals",
      newsK: "From the kettle",
      ads: "Notices",
      adsK: "Public board",
      forum: "Players",
      forumK: "Tables · board games",
      close: "Close",
      postGame: "Post a game",
      postNote: "Post a note",
      phTitleGame: "Which game, when",
      phTitle: "Notice title",
      phBody: "Short note, 280 max.",
      phNick: "Player name",
      phName: "Name",
      pin: "Pin it",
      empty: "Empty so far. Pin the first note.",
    },
    contact: {
      kicker: "When and where",
      how: "How to find us",
      s1: "1. From Charles Bridge, follow the Vltava. At the Dancing House turn up Myslíkova — a few minutes off the river.",
      s2: "2. The street gives nothing away. Myslíkova 174/23 — look for the Exafin passage, as if you already knew.",
      s3: "3. Stairs down. The tea house is under the city.",
      pass: "Prague 1 – New Town · those who know, know · Exafin passage, cellar",
      exafin: "Exafin building — large sign on the façade. Between Charles Square and the river.",
    },
    footer: {
      motto: "Tea brings people together.",
      contact: "Contact",
      hours: "Opening hours",
      hoursShort: "Mon–Thu 13–22 · Fri 13–23\nSat 14–23 · Sun 14–22",
      how: "Getting here",
      metro: "Charles Bridge trail · Vltava · Dancing House, Myslíkova",
      tram: "Metro B / tram: Karlovo náměstí · Myslíkova",
      door: "Nothing from the street. Exafin passage. Stairs down.",
      map: "Open map →",
      promo: "Promo series",
      share: "Social previews",
      partners: "Partners",
      staff: "Staff",
      icons: {
        tea: "Tea & drinks",
        teaD: "Teas from around the world, mixed drinks, mead.",
        pipes: "Hookah",
        pipesD: "Fine pipes, premium tobacco.",
        games: "Board games",
        gamesD: "Dozens of games to borrow. Come play.",
        gatcha: "Gatcha",
        gatchaD: "Spin. Free when the bill qualifies.",
        didge: "Didgeridoo",
        didgeD: "To try and to buy. Instruments with a soul.",
      },
      stories: {
        about: "About us",
        aboutD: "The story of Buddha tea house — born from a love of tea, travel and people.",
        aboutC: "Read the story",
        didge: "Didgeridoo",
        didgeD: "Authentic instruments by Tomáš Dufek. To try and to buy.",
        didgeC: "More",
        pipes: "Hookahs for sale and to rent",
        pipesD: "New and second-hand. Try them here, take them home, or borrow one.",
        pipesC: "See them",
      },
    },
    days: {
      Pondělí: "Mon",
      Úterý: "Tue",
      Středa: "Wed",
      Čtvrtek: "Thu",
      Pátek: "Fri",
      Sobota: "Sat",
      Neděle: "Sun",
    },
    book: {
      kicker: "Tell us when you’ll come",
      title: "We don’t want a slot. We want you at the table.",
      lead: "Day, wave, table from the plan. 1–4 confirmed now, 5–8 by staff, 9+ call. Street entrance through the passage, Exafin.",
      day: "Which day",
      when: "When you sit",
      party: "How many of you",
      p78: "7–8: table M1 in Small. Or two tables, or call.",
      p56: "5–6 confirmed by staff. V6, V3, V7 in Front.",
      name: "Reservation name · who is it for",
      phone: "Where we call if the table is waiting",
      phoneHint: "Czech numbers without prefix. Slovak with +421.",
      email: "Email for confirmation",
      note: "Hookah, a game, a quiet corner?",
      pick: "Pick a table on the plan",
      reserve: "Reserve",
      free: "{n} free tables this wave for {p} {people}.",
      person: "guest",
      people: "guests",
      hold: "holding",
      ok: "The table is yours",
      wait: "Waiting for staff",
      dup: "We already have this",
      waitBody: "We’ll be in touch. The group is waiting for table confirmation.",
      okBody: "Street entrance through the passage, Exafin building, down to the cellar. We’ll be waiting.",
      back: "Back to Buddha",
      all: "The whole tea house",
      first: "Room first. Then the table.",
      sit: "Where you’ll sit",
      backMap: "← whole tea house",
      taken: "taken",
      max: "max",
      upTo: "up to {n}",
      PHONE_INVALID: "Czech numbers without a prefix. Slovak and foreign with +.",
      NAME_INVALID: "Reservation name — who the table is for.",
      EMAIL_INVALID: "Email for confirmation.",
      PARTY_SIZE: "Online we take 1–8 people. More? Call.",
      CALL: "For 9 or more call +420 222 515 616.",
      TABLE: "Pick a table on the plan.",
      TABLE_SMALL: "That table is too small. Pick a larger one, or fewer people.",
      TABLE_TAKEN: "That table is already held this wave.",
    },
    waves: {
      "15:00": "Afternoon tea",
      "17:30": "Dusk settling",
      "19:30": "Evening at the pot",
      "21:30": "The quiet last",
    },
    shop: {
      kicker: "Tea house shop",
      title: "Buy for pickup.",
      lead: "Sakurač 0.3 l, Waysa 0.33 l, tea and Wookah. In-house prices. Pay on site, pick up on Myslíkova.",
      soonKicker: "Tea house shop",
      soonTitle: "Shop coming soon.",
      soonLead: "Tea, Waysa, tips, Wookah and didgeridoo. For now, buy them in the tea house. We will open pickup orders once the counter is ready.",
      soonCta: "Reserve a table",
    },
  },
  ja: {
    nav: {
      tea: "飲み物",
      pipes: "シーシャ",
      games: "ゲーム",
      fare: "メニュー",
      board: "掲示板",
      contact: "アクセス",
      shop: "ショップ",
      shopSoon: "準備中",
      book: "予約",
      menu: "メニュー",
    },
    dock: {
      where: "場所",
      hours: "営業時間",
      call: "電話",
      nav: "案内",
    },
    hero: {
      kicker: "カレル広場から数歩",
      title: "お茶。\nシーシャ。\nゲーム。\nガチャ。",
      italic: "通りは何も教えない。それから通路。それから別の時間。",
      lead: "ミスリーコヴァ通りの地下。お茶、シーシャ、急がない。",
      cta: "席を予約する",
      maps: "行き方",
    },
    mosaic: {
      offer: "お茶とドリンク",
      offerSub: "茶、酒、ソフト、食事と看板メニュー。",
      pipes: "シーシャ",
      pipesSub: "試す、買う、借りて持ち帰る。",
      gatcha: "ガチャ",
      gatchaSub: "会計のあと、回す。",
      games: "ボードゲーム",
      gamesSub: "館内の貸出ライブラリ。",
    },
    taste: {
      kicker: "店の好きなもの",
      title: "ブッダで味わって。",
      more: "詳しく",
      sakurac: "サクラチ",
      sakuracT: "やわらかい日本の定番。",
      waysa: "Waysa",
      waysaT: "アマゾンの自然なエネルギー。",
      mead: "ノルウェーのミード",
      meadT: "北の蜂蜜酒、ゆっくりした夜に。",
    },
    bookBand: {
      kicker: "予約",
      title: "かんたんに。",
      lead: "日、時間帯、席。1〜4名はすぐ確定、5〜8名はスタッフ確認。",
      cta: "席を予約する",
    },
    promo: {
      kicker: "プロモ",
      title: "息をする広間。",
      all: "シリーズ全部 →",
    },
    reasons: {
      kicker: "今日来る理由",
      title: "ふたり。仲間と。もう少し大きな席。",
      duo: "ふたりで",
      duoT: "一つの急須、二つの碗。急がない夜。",
      friends: "仲間と",
      friendsT: "ゲーム、お茶、シーシャ。時間のある座り方。",
      party: "グループ",
      partyT: "5〜8名はオンライン。9名以上はお電話で。",
    },
    pipeSec: {
      kicker: "シーシャ",
      title: "分では数えない夜。",
      body: "Adalya 229 Kč、Cult と Serbetli 289 Kč。ドリンク付き、18歳以上。隣のシーシャバーより手頃。持ち帰りレンタルもできます。",
    },
    gamesSec: {
      kicker: "ボードゲーム",
      title: "借りて、遊ぶ。",
      body: "館内のライブラリ。カタン、カルカソンヌなど数十タイトル。デポジット 200 Kč。",
      cta: "ゲーム一覧 →",
    },
    gatchaSec: {
      kicker: "ガチャ",
      title: "会計のあと、回す。",
      from: "レシート",
      small: "1,500 Kč",
      eqS: "＝小さいガチャ。",
      from2: "から",
      big: "2,000 Kč",
      eqL: "＝大きいガチャ。",
      note: "来店のごほうび。機械ではない。",
      cta: "ガチャの仕組み →",
    },
    hh: {
      badge: "月〜木 · 13:00–15:00",
      kicker: "ハッピーアワー",
      title: "シーシャの割引。",
      deal: "1+1、一杯分の値段。",
      lead: "仲間とどうぞ。二本で一本分。違う銘柄なら高い方が請求されます。",
      r1: "15時まで、一緒に注文。最低二人。",
      r2: "同じ価格帯。違うなら高い方。",
      r3: "「10本目無料」カードとは併用不可。",
      cta: "午後を予約する",
    },
    reviews: {
      kicker: "広間の声 · 4.4 / 5",
      title: "私たちが言っているのではない。",
      prev: "前のレビュー",
      next: "次のレビュー",
    },
    about: {
      kicker: "私たち",
      title: "茶と旅と人への愛から。",
      body: "ミスリーコヴァはカレル4世のころから川から広場へ続く。茶房はその下——ゆっくりするための地下。お茶、シーシャ、ゲーム。入口は通りからエクサフィンの通路。",
    },
    didge: {
      kicker: "ディジュリドゥ",
      title: "魂のある楽器。",
      body: "Tomáš Dufek の本物。広間で試して、買える。",
      cta: "ショップのディジュリドゥ →",
    },
    matcha: {
      badge: "まもなく終了",
      kicker: "季節",
      title: "抹茶メニュー。",
      note: "ソフト 120 g、または3スクープ 180 g。ソフトがなくなったらスクープ 120 g。",
      book: "予約",
      ig: "Instagram",
      n1: "抹茶フロート",
      t1: "泡立てた抹茶にソーダ、いちごシロップ、抹茶アイス。",
      n2: "酔いいちご",
      t2: "ウォッカとナッツリキュール、つぶしたいちご、きび糖、抹茶アイス。",
      n3: "抹茶ビール",
      t3: "Oxymoron 13° ラガーに泡立てた抹茶。",
      n4: "抹茶ジンソーダ",
      t4: "泡立てた抹茶にソーダ、いちごシロップ、Roku ジン。",
      n5: "抹茶ラテフロート",
      t5: "アイス抹茶ラテに抹茶アイス。",
      n6: "アイスカップ",
      t6: "抹茶アイスにホイップといちご。",
    },
    board: {
      kicker: "茶房の掲示板",
      rss: "RSS →",
      tabs: "掲示のレーン",
      news: "茶とお知らせ",
      newsK: "急須から",
      ads: "案内",
      adsK: "公開ボード",
      forum: "プレイヤー",
      forumK: "卓 · ボードゲーム",
      close: "閉じる",
      postGame: "募集を貼る",
      postNote: "メモを貼る",
      phTitleGame: "何のゲーム、いつ",
      phTitle: "見出し",
      phBody: "短いメモ、280字まで。",
      phNick: "プレイヤー名",
      phName: "名前",
      pin: "ピンする",
      empty: "まだ空。最初のメモを。",
    },
    contact: {
      kicker: "いつ、どこ",
      how: "行き方",
      s1: "1. カレル橋からヴルタヴァ沿いに。ダンシングハウスでミスリーコヴァへ。川から数分。",
      s2: "2. 通りからは見えない。Myslíkova 174/23。エクサフィンの通路を、知っている人のように。",
      s3: "3. 階段を下りる。茶房は街の下。",
      pass: "プラハ1 · 新市街 · 知る人ぞ知る · エクサフィン通路、地下",
      exafin: "Exafin の建物——ファサードの大きな文字。カレル広場と川のあいだ。",
    },
    footer: {
      motto: "茶は人をつなぐ。",
      contact: "連絡先",
      hours: "営業時間",
      hoursShort: "月〜木 13–22 · 金 13–23\n土 14–23 · 日 14–22",
      how: "アクセス",
      metro: "カレル橋の流れ · ヴルタヴァ · ダンシングハウス、ミスリーコヴァ",
      tram: "メトロ B / 路面電車: カレル広場 · ミスリーコヴァ",
      door: "通りからは何もない。エクサフィン通路。階段を下りる。",
      map: "地図を開く →",
      promo: "プロモ",
      share: "シェア画像",
      partners: "協力",
      staff: "スタッフ",
      icons: {
        tea: "お茶とドリンク",
        teaD: "世界のお茶、カクテル、ミード。",
        pipes: "シーシャ",
        pipesD: "上質なパイプ、プレミアムタバコ。",
        games: "ボードゲーム",
        gamesD: "貸出できる数十のゲーム。",
        gatcha: "ガチャ",
        gatchaD: "会計が条件を満たせば無料。",
        didge: "ディジュリドゥ",
        didgeD: "試して、買える。魂のある楽器。",
      },
      stories: {
        about: "私たち",
        aboutD: "ブッダ茶房の物語。茶と旅と人への愛から。",
        aboutC: "物語を読む",
        didge: "ディジュリドゥ",
        didgeD: "Tomáš Dufek の本物。試して、買える。",
        didgeC: "もっと",
        pipes: "シーシャの販売とレンタル",
        pipesD: "新品も中古も。ここで試して、持ち帰る、借りる。",
        pipesC: "見る",
      },
    },
    days: {
      Pondělí: "月",
      Úterý: "火",
      Středa: "水",
      Čtvrtek: "木",
      Pátek: "金",
      Sobota: "土",
      Neděle: "日",
    },
    book: {
      kicker: "いつ来るか教えて",
      title: "枠ではなく、席にいてほしい。",
      lead: "日、時間帯、図面の席。1〜4名はすぐ、5〜8名はスタッフ、9名以上は電話。入口は通りから通路、Exafin。",
      day: "来る日",
      when: "着く時間",
      party: "人数",
      p78: "7〜8名: 小部屋の M1。または二卓、またはお電話。",
      p56: "5〜6名はスタッフ確認。前室の V6、V3、V7。",
      name: "予約名 · どなたの席か",
      phone: "席が待っているときの電話",
      phoneHint: "チェコは市外局番なし。スロバキアは +421。",
      email: "確認用メール",
      note: "シーシャ、ゲーム、静かな隅？",
      pick: "図面で席を選ぶ",
      reserve: "予約する",
      free: "この時間帯、{p}{people}向けの空きは {n} 卓。",
      person: "名",
      people: "名",
      hold: "確保中",
      ok: "席はあなたのもの",
      wait: "スタッフ確認待ち",
      dup: "すでに受けています",
      waitBody: "ご連絡します。グループの席確認を待っています。",
      okBody: "通りから通路、Exafin の建物、地下へ。待っています。",
      back: "ブッダへ戻る",
      all: "茶房全体",
      first: "まず部屋。それから席。",
      sit: "座る場所",
      backMap: "← 茶房全体",
      taken: "使用中",
      max: "最大",
      upTo: "最大 {n} 名",
      PHONE_INVALID: "チェコは市外局番なし。国外は + から。",
      NAME_INVALID: "予約名——どなたの席か。",
      EMAIL_INVALID: "確認用メール。",
      PARTY_SIZE: "オンラインは 1〜8 名。それ以上はお電話で。",
      CALL: "9名以上は +420 222 515 616。",
      TABLE: "図面で席を選んでください。",
      TABLE_SMALL: "この卓は人数に対して小さいです。大きい席か、人数を減らしてください。",
      TABLE_TAKEN: "この時間帯、その席は埋まっています。",
    },
    waves: {
      "15:00": "午後のお茶",
      "17:30": "ゆっくり暮れる",
      "19:30": "急須の夜",
      "21:30": "静かな最後",
    },
    shop: {
      kicker: "茶房の店",
      title: "受け取り購入。",
      lead: "サクラチ 0.3 l、Waysa 0.33 l、茶と Wookah。店内価格。現地払い、ミスリーコヴァで受け取り。",
      soonKicker: "茶房の店",
      soonTitle: "オンラインショップ準備中。",
      soonLead: "茶、Waysa、マウスピース、Wookah、ディジュリドゥ。今は店頭で。受け取りの準備ができたらオンラインを開きます。",
      soonCta: "席を予約する",
    },
  },
} as const;
